import { v4 as uuidv4 } from 'uuid';
import { Recipe } from '../types/recipe';

export const SEED_RECIPES: Recipe[] = [
  {
    id: uuidv4(),
    title: 'Creamy Garlic Pasta',
    description: 'A rich and creamy pasta dish with roasted garlic, parmesan, and fresh herbs. Ready in 30 minutes!',
    category: 'dinner',
    ingredients: [
      { id: uuidv4(), name: 'Pasta', amount: '400', unit: 'g' },
      { id: uuidv4(), name: 'Garlic', amount: '6', unit: 'cloves' },
      { id: uuidv4(), name: 'Cream', amount: '200', unit: 'ml' },
      { id: uuidv4(), name: 'Parmesan', amount: '80', unit: 'g' },
      { id: uuidv4(), name: 'Butter', amount: '2', unit: 'tbsp' },
      { id: uuidv4(), name: 'Basil', amount: 'handful', unit: '' },
      { id: uuidv4(), name: 'Salt', amount: 'to taste', unit: '' },
    ],
    steps: [
      { id: uuidv4(), order: 0, description: 'Boil salted water and cook pasta until al dente. Reserve 1 cup of pasta water.' },
      { id: uuidv4(), order: 1, description: 'In a large pan, melt butter over medium heat. Add minced garlic and cook for 2-3 minutes until fragrant.' },
      { id: uuidv4(), order: 2, description: 'Pour in the cream and bring to a gentle simmer. Season with salt and pepper.' },
      { id: uuidv4(), order: 3, description: 'Add drained pasta to the sauce. Toss to combine, adding pasta water as needed.' },
      { id: uuidv4(), order: 4, description: 'Stir in grated parmesan and fresh basil. Serve immediately.' },
    ],
    tags: ['quick', 'italian', 'creamy'],
    isFavorite: true,
    timesCooked: 7,
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: uuidv4(),
    title: 'Spinach Tomato Cheese Omelette',
    description: 'A fluffy protein-packed omelette with fresh spinach, juicy tomatoes, and melted cheese.',
    category: 'breakfast',
    ingredients: [
      { id: uuidv4(), name: 'Eggs', amount: '3', unit: '' },
      { id: uuidv4(), name: 'Spinach', amount: '1 handful', unit: '' },
      { id: uuidv4(), name: 'Tomato', amount: '1', unit: 'medium' },
      { id: uuidv4(), name: 'Cheese', amount: '30', unit: 'g' },
      { id: uuidv4(), name: 'Butter', amount: '1', unit: 'tsp' },
      { id: uuidv4(), name: 'Salt', amount: 'pinch', unit: '' },
    ],
    steps: [
      { id: uuidv4(), order: 0, description: 'Beat eggs with a pinch of salt and pepper in a bowl.' },
      { id: uuidv4(), order: 1, description: 'Heat butter in a non-stick pan over medium heat. Add spinach and cook until wilted.' },
      { id: uuidv4(), order: 2, description: 'Pour in beaten eggs. Cook until edges start to set.' },
      { id: uuidv4(), order: 3, description: 'Add diced tomato and grated cheese on one half. Fold the omelette and serve.' },
    ],
    tags: ['high-protein', 'quick', 'vegetarian'],
    isFavorite: false,
    timesCooked: 12,
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: uuidv4(),
    title: 'Avocado & Lime Guacamole',
    description: 'Fresh, zesty guacamole perfect for dipping. Made with ripe avocados, lime, cilantro, and onion.',
    category: 'snack',
    ingredients: [
      { id: uuidv4(), name: 'Avocado', amount: '2', unit: 'ripe' },
      { id: uuidv4(), name: 'Lime', amount: '1', unit: '' },
      { id: uuidv4(), name: 'Cilantro', amount: '2 tbsp', unit: '' },
      { id: uuidv4(), name: 'Onion', amount: '¼', unit: 'small' },
      { id: uuidv4(), name: 'Tomato', amount: '1', unit: 'small' },
      { id: uuidv4(), name: 'Salt', amount: 'to taste', unit: '' },
    ],
    steps: [
      { id: uuidv4(), order: 0, description: 'Cut avocados in half, remove pits, and scoop flesh into a bowl.' },
      { id: uuidv4(), order: 1, description: 'Mash avocados with a fork to your desired consistency.' },
      { id: uuidv4(), order: 2, description: 'Add lime juice, finely diced onion, chopped cilantro, and diced tomato.' },
      { id: uuidv4(), order: 3, description: 'Mix well, season with salt, and serve immediately with tortilla chips.' },
    ],
    tags: ['vegan', 'dip', 'fresh', 'mexican'],
    isFavorite: true,
    timesCooked: 4,
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: uuidv4(),
    title: 'Classic Chicken Rice Soup',
    description: 'A hearty, warming soup with tender chicken, vegetables, and rice. Perfect comfort food.',
    category: 'soup',
    ingredients: [
      { id: uuidv4(), name: 'Chicken', amount: '500', unit: 'g' },
      { id: uuidv4(), name: 'Rice', amount: '½ cup', unit: '' },
      { id: uuidv4(), name: 'Carrot', amount: '2', unit: '' },
      { id: uuidv4(), name: 'Celery', amount: '2 stalks', unit: '' },
      { id: uuidv4(), name: 'Onion', amount: '1', unit: '' },
      { id: uuidv4(), name: 'Garlic', amount: '3 cloves', unit: '' },
      { id: uuidv4(), name: 'Broth', amount: '1.5 L', unit: '' },
      { id: uuidv4(), name: 'Salt', amount: 'to taste', unit: '' },
    ],
    steps: [
      { id: uuidv4(), order: 0, description: 'In a large pot, sauté diced onion, carrots, and celery in oil for 5 minutes.' },
      { id: uuidv4(), order: 1, description: 'Add minced garlic and cook for 1 minute more.' },
      { id: uuidv4(), order: 2, description: 'Add chicken pieces and pour in the broth. Bring to a boil.' },
      { id: uuidv4(), order: 3, description: 'Reduce heat, add rice, and simmer for 20-25 minutes until chicken is cooked through.' },
      { id: uuidv4(), order: 4, description: 'Remove chicken, shred it, return to pot. Season and serve hot.' },
    ],
    tags: ['comfort-food', 'hearty', 'winter'],
    isFavorite: false,
    timesCooked: 3,
    prepTime: 15,
    cookTime: 35,
    servings: 6,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: uuidv4(),
    title: 'Banana Oat Honey Pancakes',
    description: 'Healthy and delicious pancakes made with ripe bananas, oats, and a drizzle of honey. Gluten-friendly!',
    category: 'breakfast',
    ingredients: [
      { id: uuidv4(), name: 'Banana', amount: '2', unit: 'ripe' },
      { id: uuidv4(), name: 'Oats', amount: '1 cup', unit: '' },
      { id: uuidv4(), name: 'Eggs', amount: '2', unit: '' },
      { id: uuidv4(), name: 'Honey', amount: '2 tbsp', unit: '' },
      { id: uuidv4(), name: 'Milk', amount: '¼ cup', unit: '' },
      { id: uuidv4(), name: 'Vanilla', amount: '1 tsp', unit: '' },
    ],
    steps: [
      { id: uuidv4(), order: 0, description: 'Blend oats into flour using a blender.' },
      { id: uuidv4(), order: 1, description: 'Mash bananas in a bowl. Add eggs, honey, milk, and vanilla. Mix well.' },
      { id: uuidv4(), order: 2, description: 'Fold in oat flour until combined. Let batter rest 5 minutes.' },
      { id: uuidv4(), order: 3, description: 'Cook spoonfuls of batter on a greased pan over medium heat, 2-3 min per side.' },
      { id: uuidv4(), order: 4, description: 'Serve with extra honey, sliced bananas, or fresh berries.' },
    ],
    tags: ['healthy', 'gluten-friendly', 'sweet'],
    isFavorite: true,
    timesCooked: 8,
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_PANTRY = [
  'tomato', 'spinach', 'cheese', 'eggs', 'garlic', 'onion',
  'avocado', 'lemon', 'chicken', 'rice', 'pasta', 'butter',
];
